model: yolov5s-cls.pt
data: imagenette160
epochs: 35
batch_size: 16
imgsz: 224
nosave: false
cache: null
device: '0'
workers: 8
project: ../runs/train-cls
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 0.0001
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: ../runs/train-cls/exp8
